### ISSUE TITLE
[Question] Border radius

### ISSUE THREAD

**Issue by tobacode** [wootra/svg-table#14]
Hi,
Thank you for the fantastic work!
Is the ability to add rounded corners on your roadmap?
Thanks a lot!

**Comment by wootra** [comment]
Thanks for being interested in svg-table. 
I can start working on rounded corner functionality. 
Great idea!

**Comment by wootra** [comment]
I added border radius functionality. Checkout this: https://www.svg-table.com/basic-usage

**Comment by tobacode** [comment]
This looks awesome, thanks! I will give it a try soon!
If I understand correctly, with unequal rx and ry values I am able to adjust the corner's appearance, and with equal values I get a quarter circle?

**Comment by wootra** [comment]
> This looks awesome, thanks! I will give it a try soon! If I understand correctly, with unequal rx and ry values I am able to adjust the corner's appearance, and with equal values I get a quarter circle?

That's correct. you can use the same number for evenly rounded shape.
